---
- name: Deploy services into local services
  hosts: localhost
  become: yes
  become_user: root
  gather_facts: false
  vars_files:
    - secrets.yml
  vars:
    app_user: appuser
    app_dir: /opt/STOCK
    nexus_url: http://localhost:5050/repository/stockApp-releases/org/sid
  tasks:

    # ENSURE APACHE IS RUNNING
    # - name: Ensure Apache is Installed
    #   ansible.builtin.dnf:
    #     name: httpd
    #     state: present

    # - name: Start Apache
    #   ansible.builtin.service:
    #     name: httpd
    #     state: started

    # APPLICATION COPY INTO DIRECTORY
    - name: Create Project Directory if don't exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - /var/www/html/STOCK/frontend
        - /opt/STOCK/
        - /tmp/STOCK/

    - name: Download Front End files into Apache Directories From Nexus
      ansible.builtin.get_url:
        url: "{{ nexus_url }}/frontend/latest/frontend-latest.tar.gz"
        dest: "/tmp/STOCK"
        url_username: "{{ nexus_user }}"
        url_password: "{{ nexus_password }}"
        force_basic_auth: yes

    - name: Unarchive the zip
      ansible.builtin.unarchive:
        src: "/tmp/STOCK/frontend-latest.tar.gz"
        dest: "/var/www/html/STOCK/frontend"
        remote_src: yes
        

    - name: Download backEnd files From Nexus into App Directory
      ansible.builtin.get_url:
        url: "{{ nexus_url }}/{{ item }}/latest/{{ item }}-latest.jar"
        dest: "{{ app_dir }}"
        url_username: "{{ nexus_user }}"
        url_password: "{{ nexus_password }}"
        force_basic_auth: yes
      loop:
        - stock-service
        - discovery-service
        - gateway-service


    # USER & DIR OWNERSHIP
    - name: Create App User If doesn't exist
      ansible.builtin.user:
        name: "{{ app_user }}"
        shell: /sbin/nologin
        create_home: no
        state: present

    - name: Ensure Application Ownership
      ansible.builtin.file:
        path: "{{ app_dir }}"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        recurse: yes

      
    # CREATING SYS SERVICES FOR EACH SERVICE
    - name: Find Jars
      ansible.builtin.find:
        paths: "{{ app_dir }}"
        patterns: "*.jar"
      register: jar_files

    - name: Create SystemD Services
      ansible.builtin.template:
        src: java-service.service.j2
        dest: "/etc/systemd/system/{{ item.path | basename | regex_replace('-0.0.1-SNAPSHOT.jar','')}}.service"
        mode: '0644'
      loop: "{{ jar_files.files }}"
      notify: Reload System

    - name: Ensure Apache Configuration Exist
      ansible.builtin.copy:
        src: stockFront.conf
        dest: "/etc/httpd/conf.d"
      notify: restart apache2

    - name: Ensure Backend Services running
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        daemon_reload: yes
      loop:
        - stock-service
        - gateway-service
        - discovery-service


  handlers:
    - name: Reload System
      ansible.builtin.systemd:
        daemon_reload: yes
    - name: restart apache2
      ansible.builtin.systemd:
        name: httpd
        state: restarted
        daemon_reload: yes
# ansible role
# group vars