spring.application.name=stock-service
server.port=8081

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:stockdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# OAuth2 Resource Server Configuration - Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/stock-adria
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/stock-adria/protocol/openid-connect/certs

# Logging
logging.level.org.sid.stockservice=DEBUG
logging.level.org.springframework.security=DEBUG
