spring.application.name=gateway-service
server.port=8888

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Gateway Routes Configuration
spring.cloud.gateway.routes[0].id=stock-service
spring.cloud.gateway.routes[0].uri=lb://STOCK-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/companies/**, /api/stocks/**

# Enable discovery locator (optional - for automatic routing)
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# OAuth2 Resource Server Configuration - Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/stock-adria
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/stock-adria/protocol/openid-connect/certs

# CORS Configuration
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true
