input {
  beats {
    port => 5044
  }
  tcp {
    port => 5000
    codec => json
  }
}

filter {

  #
  # 1. Extract log level if present
  #
  grok {
    match => {
      "message" => [
        "\[%{LOGLEVEL:log_level}\] %{GREEDYDATA:log_message}",
        "\[%{WORD:pipeline_tag}\] %{GREEDYDATA:log_message}"
      ]
    }
    tag_on_failure => []
  }
  # Extract Jenkins build number
  grok {
  match => {
    "path" => "/var/lib/jenkins/jobs/%{DATA:job_name}/builds/%{NUMBER:build_number}/log"
  }
  tag_on_failure => []
}
  #
  # 2. Detect Jenkins stage names
  #
  if "[Pipeline] { (" in [message] {
    grok {
      match => { "message" => "\[Pipeline\] \{ \(%{DATA:stage_name}\)" }
      tag_on_failure => []
    }
  }

  #
  # 3. Extract artifact path (Maven build)
  #
  if "Building jar:" in [message] {
    grok {
      match => { "message" => "Building jar: %{DATA:artifact_path}" }
      tag_on_failure => []
    }
  }

  #
  # 4. Detect build final status
  #
  if "Finished:" in [message] {
    grok {
      match => { "message" => "Finished: %{WORD:build_status}" }
      tag_on_failure => []
    }
  }

  #
  # 5. Detect Maven errors
  #
  if "[ERROR]" in [message] {
    grok {
      match => { "message" => "\[ERROR\] %{GREEDYDATA:error_message}" }
      tag_on_failure => []
    }
    mutate {
      add_field => { "error_detected" => "true" }
    }
  }

  #
  # 6. Cleanup
  #
  mutate {
    remove_field => ["host", "agent", "input", "ecs"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "jenkins-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
